name: Deploy Firebase Express API

on:
  push:
    branches:
      - development
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Decode Firebase Credentials
        run: |
          echo -n ${{ secrets.APP_FIREBASE_ADMIN_JSON }} | base64 --decode > $HOME/firebase-credentials.json


      - name: Authenticate with Firebase
        uses: google-github-actions/auth@v2
        with:
          credentials_json: $HOME/firebase-credentials.json

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Clear Staging Database (Only for Development)
        if: github.ref == 'refs/heads/development'
        run: |
          echo "Clearing Staging Database..."
          firebase database:remove / --confirm --project ${{ secrets.APP_FIREBASE_PROJECT_ID }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/development'
        run: |
          echo "Deploying Staging Firebase Functions..."
          firebase deploy --only functions --project ${{ secrets.APP_FIREBASE_PROJECT_ID }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying Production Firebase Functions..."
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROD_PROJECT }}
